import prisma from "@/lib/prisma";
import StickerGrid from "@/components/StickerGrid";
import { auth } from "@/lib/auth";

export default async function AdminStickersPage() {
  const stickers = await prisma.sticker.findMany({
    orderBy: { createdAt: "desc" },
    take: 100,
    select: {
      id: true,
      slug: true,
      title: true,
      description: true,
      category: true,
      subCategory: true,
      rarity: true,
      isLive: true,
      cloudinaryUrl: true,
      thumbnailUrl: true,
      type: true,
      fileSizeKb: true,
      widthPx: true,
      heightPx: true,
      durationMs: true,
      ocrText: true,
      languages: true,
      hasTextOverlay: true,
      sourceName: true,
      originalUrl: true,
      dominantEmotion: true,
      emotionScores: true,
      energyLevel: true,
      tone: true,
      tags: true,
      scenarioFit: true,
      useCase: true,
      phash: true,
      isNsfw: true,
      nsfwScore: true,
      moderationNotes: true,
      verifiedBy: true,
      verifiedAt: true,
      baseScoreWeight: true,
      playCount: true,
      winCount: true,
      voteCount: true,
      avgClipScore: true,
      avgVoteScore: true,
      hypeCount: true,
      timesFavourited: true,
      reportCount: true,
      isFlagged: true,
      clipTags: true,
      createdAt: true,
      updatedAt: true,
    },
  });

  return <StickerGrid stickers={stickers} />;
}
